version: '3.8'
services:
  express-server:
    image: dev1800/express-api:latest
    build:
      context: .
    volumes:
      - ./:/app
      - /app/node_modules
    deploy:
      replicas: 4
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 10s
    environment:
      - PORT=5000

  server-nginx:
    image: nginx:stable-alpine
    container_name: server-nginx-c 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "5000:80"
    depends_on:
      - express-server
      
